BaSP-TG-1: Super admins list and delete
BaSP-a2022/marta-a-trackgenix-app pull request #1
Opened 2022-10-31 23:35 UTC by elias-92

2022-11-01 14:39 UTC, martumoser requested changes
Please add a description to the PR

public/assets/images/btn-add.svg. -> should be a button instead of a svg

2022-11-01 14:39 UTC, martumoser commented on src/Components/SuperAdmins/Form/index.js
> +import { useState } from 'react';
If you are solving ticket TG-1: List and delete super admin this form is not included on this ticket. This form should be on another PR. If you are going to resolve both tickets together you should mention that on PR description and on the ticket

2022-11-01 14:39 UTC, martumoser commented on src/Components/SuperAdmins/index.js
> +        deleteSA={deleteSA}
replace SA for SuperAdmin

2022-11-01 14:39 UTC, martumoser commented on src/Components/SuperAdmins/index.js
> +        superAdmin={superAdmins}
superAdmin should be plural: superAdmins

2022-11-01 14:39 UTC, martumoser commented on src/Components/SuperAdmins/List/list.module.css
> +  border-bottom: 1px solid black;
Please keep consistency between the use of colors on hex (example line 26) and the name of colors. we suggest to use colors on hex

2022-11-01 14:39 UTC, martumoser commented on src/Components/SuperAdmins/index.js
> +        state={modal}
Replace for: modal={modal} and setModal={setModal}

2022-11-01 14:39 UTC, martumoser commented on src/Components/SuperAdmins/index.js
>  function SuperAdmins() {
Replace function for const and arrow function. Use ECMAScript 6

2022-11-01 20:06 UTC, elias-92 commented on src/Components/SuperAdmins/Form/index.js
> +import { useState } from 'react';
OK I would go in the other PR then.

2022-11-01 20:57 UTC, elias-92 commented on src/Components/SuperAdmins/Form/index.js
> +import { useState } from 'react';
I looked at the ticket and it says to create the redirection with the add and edit button, that's why I put that empty form.

2022-11-02 01:12 UTC, martumoser requested changes
Please add a description to the PR and delete add admin icon. Replace with a button

2022-11-02 01:12 UTC, martumoser commented on src/Components/SuperAdmins/List/index.js
> +const ListSuperAdmins = ({ superAdmin, modal, setModal, setId }) => {
superAdmin is plural because it is the array with all super admins

2022-11-02 01:12 UTC, martumoser commented on src/Components/SuperAdmins/Modal/modal.module.css
> +  color: white;
Please keep consistency between the use of colors on hex or with the color name. We suggest to use color hex

2022-11-02 01:24 UTC, elias-92 commented on src/Components/SuperAdmins/Modal/modal.module.css
> +  color: white;
hahaha I missed it, god

2022-11-03 15:56 UTC, Martinzancocchia submitted a review, later dismissed

2022-11-03 21:36 UTC, martumoser submitted a review, later dismissed

2022-11-04 12:57 UTC, martumoser approved these changes

2022-11-05 04:01 UTC, NicolasGulam commented
Revise trello, comments were done there

2022-11-05 17:24 UTC, Martinzancocchia approved these changes

2022-11-05 17:24 UTC, NicolasGulam approved these changes

2022-11-05 17:25 UTC, merged