BaSP-TG-27: create input and select component
BaSP-a2022/marta-a-trackgenix-app pull request #12
Opened 2022-11-06 20:30 UTC by elias-92

Create input and select components, leaving a screenshot of how to use it. 

![implementation input and select](https://user-images.githubusercontent.com/92071674/200193542-3942a808-dcfb-4869-a94b-211fdf690ec9.png)

2022-11-06 21:07 UTC, Baldizan approved these changes

2022-11-07 03:39 UTC, Baldizan approved these changes

2022-11-07 15:37 UTC, martumoser requested changes

2022-11-07 15:37 UTC, martumoser commented on src/Components/Shared/Input/index.js
> +};
Please leave a space between 22 and 23

2022-11-07 16:09 UTC, martumoser approved these changes

2022-11-08 13:24 UTC, LucianaPrat approved these changes

2022-11-08 13:27 UTC, merged