BaSP-29: component table implementation
BaSP-a2022/marta-a-trackgenix-app pull request #16
Opened 2022-11-09 02:30 UTC by LucianaPrat

**Implementation of the shared components in the Project entity:**

- Table
- Form
- Modal
- Button
- 

**React Router Implementation**

2022-11-10 14:34 UTC, martumoser requested changes

2022-11-10 14:34 UTC, martumoser commented on src/Components/Shared/Input/index.js
> +        ))}
This correction is okey but take in mind that you are modifying a shared component which is used on other parts of the code so be careful when you do this type of changes. Check with the team this change and maybe you have to create a hotfix pr to solve this and implement this change

2022-11-10 14:34 UTC, martumoser commented on src/Components/Shared/Table/Row/index.js
> +
This change is not correct. Those functions are received as props

2022-11-10 14:34 UTC, martumoser commented on src/Components/Projects/index.js
> +        }))}
I don't understand this. Why you are sending a button on the data? move this logic outside the return to have a clear code

2022-11-10 15:20 UTC, LucianaPrat commented on src/Components/Shared/Input/index.js
> +        ))}
We discussed this with the team, should I create an independent PR?

2022-11-10 15:37 UTC, LucianaPrat commented on src/Components/Projects/index.js
> +        }))}
I did it that way because the Table component couldn't add a new custom column, and since project was the only one that would do this, we decided not to make the modifications to the table.
I will modify that part to make the code cleaner.

2022-11-10 15:40 UTC, martumoser commented on src/Components/Shared/Input/index.js
> +        ))}
Okey, leave on this pr.

2022-11-11 00:51 UTC, elias-92 commented on src/Components/Projects/Form/form.js
> +    var today = new Date(d);
you shouldn't use var.

2022-11-11 00:54 UTC, elias-92 commented on src/Components/Projects/Form/form.js
> +            id: status == 'Active',
You should use triple equal.

2022-11-11 00:55 UTC, elias-92 reviewed
Comments

2022-11-11 01:23 UTC, Martinzancocchia approved these changes

2022-11-11 21:06 UTC, Baldizan commented on src/Components/Projects/Form/form.js
> +    setEmployee({ ...employee, role: e.target.value });
these 2 functions can be handled by the "onChange" function, if the "name" is defined on the "Select" components

2022-11-11 23:57 UTC, mr-valen approved these changes
I found some bugs that I will report on Trello.

2022-11-11 23:58 UTC, mr-valen commented
"fature/TG-29/" should be "feature/TG-29/"

2022-11-12 01:07 UTC, Baldizan approved these changes

2022-11-12 01:09 UTC, merged