BaSP TG-31: Timesheet components implementation
BaSP-a2022/marta-a-trackgenix-app pull request #17
Opened 2022-11-09 02:47 UTC by Baldizan

Shared Table, Button, Form, Inputs and Modal implementation into timesheet screens.

2022-11-10 00:35 UTC, Martinzancocchia approved these changes

2022-11-10 03:19 UTC, LucianaPrat approved these changes

2022-11-10 14:37 UTC, martumoser submitted a review, later dismissed
Why you are adding an empty file on Table row shared component?

2022-11-10 14:37 UTC, martumoser commented on src/Components/Shared/Input/index.js
> +        required={required}
This correction is okey but take in mind that you are modifying a shared component which is used on other parts of the code so be careful when you do this type of changes. Check with the team this change and maybe you have to create a hotfix pr to solve this and implement this change

2022-11-11 15:38 UTC, martumoser requested changes

2022-11-11 15:38 UTC, martumoser commented on src/Components/TimeSheets/TimeSheetsForm/index.js
> +          arrayToMap={project()}
project() means that you are executing the function. You have to send project with execute it

2022-11-11 15:38 UTC, martumoser commented on src/Components/TimeSheets/TimeSheetsTable/index.js
> +        }))}
move this logic outside the return to have a clean code

2022-11-11 21:41 UTC, NicolasGulam approved these changes

2022-11-11 21:44 UTC, merged