BaSP-29: shared components implementation (Super-Admins)
BaSP-a2022/marta-a-trackgenix-app pull request #18
Opened 2022-11-09 02:48 UTC by Martinzancocchia

shared components:
[implemented] Table
[in progress] Modal
[not implemented] Form
[not implemented] Imput

2022-11-09 22:35 UTC, Baldizan commented
The arrow images were also added on TG-31. It would be better to remove them, otherwise files may duplicate.

2022-11-09 22:41 UTC, Martinzancocchia commented on src/Components/Shared/Table/Row/row.module.css
> + .tr {
done!

2022-11-09 22:41 UTC, Martinzancocchia commented
> The arrow images were also added on TG-31. It would be better to remove them, otherwise files may duplicate.
Done!!!

2022-11-10 01:05 UTC, Baldizan commented on src/Components/SuperAdmins/Form/index.js
> +    console.log(selectedSuperAdmin);
please remove this console log

2022-11-10 01:07 UTC, Baldizan approved these changes

2022-11-10 21:45 UTC, LucianaPrat requested changes

2022-11-10 21:45 UTC, LucianaPrat commented on src/Components/Shared/Table/Row/row.module.css
> +  min-width: 150px;
There should be no changes to this shared component

2022-11-10 21:45 UTC, LucianaPrat commented on src/Components/Shared/Table/index.js
> +              editItem={() => editItem(item)}
There should be no changes to this shared component

2022-11-10 21:45 UTC, LucianaPrat commented on src/Components/Shared/Table/table.module.css
> +  justify-content: flex-start;
There should be no changes to this shared component

2022-11-10 21:45 UTC, LucianaPrat commented on src/Components/SuperAdmins/Form/index.js
> +          title={'Name'}
should be Title = "Name" , to be consistent with the line above

2022-11-10 21:45 UTC, LucianaPrat commented on src/Components/SuperAdmins/Form/index.js
> +          title={'Last Name'}
should be Title = "Name" , to be consistent with the line above

2022-11-10 21:45 UTC, LucianaPrat commented on src/Components/SuperAdmins/Form/index.js
> +          title={'Password'}
should be Title = "Name" , to be consistent with the line above

2022-11-10 21:45 UTC, LucianaPrat commented on src/Components/SuperAdmins/Form/index.js
> +          title={'Email'}
should be Title = "Name" , to be consistent with the line above

2022-11-10 21:45 UTC, LucianaPrat commented on src/Components/SuperAdmins/super-admins.module.css
>    align-items: center;
.container should go one line below , align-item should go below flex-direction

2022-11-10 21:45 UTC, LucianaPrat commented on src/Components/SuperAdmins/index.js
> +      {modalDisplay && (
should be {modalDisplay && (.....)}

2022-11-10 23:00 UTC, LucianaPrat approved these changes

2022-11-11 21:40 UTC, NicolasGulam approved these changes

2022-11-12 03:30 UTC, merged