BaSP-TG-30: Admins implement shared components
BaSP-a2022/marta-a-trackgenix-app pull request #19
Opened 2022-11-09 03:03 UTC by GuidoG95

2022-11-10 18:16 UTC, LucianaPrat commented on src/Components/Admins/Form/form.module.css
> +  }
incorrect indentation

2022-11-10 18:39 UTC, LucianaPrat requested changes

2022-11-10 18:39 UTC, LucianaPrat commented on src/Components/Admins/Form/index.js
> +  const [selectedAdmin] = useState(history.location.state);
I think you shouldn't use useState , since it's not a state that should change .  example: `const selectedAdminId = history.location.state?.id;`

2022-11-10 18:39 UTC, LucianaPrat commented on src/Components/Admins/Form/index.js
> +          title={'Name'}
could be changed to "Name" as in the previous line

2022-11-10 18:39 UTC, LucianaPrat commented on src/Components/Admins/Form/index.js
> +          title={'Last Name'}
same above

2022-11-10 18:39 UTC, LucianaPrat commented on src/Components/Admins/Form/index.js
> +      {modalDisplay ? (
change for {modalDisplay && ( ... )}

2022-11-10 18:39 UTC, LucianaPrat commented on src/Components/Admins/index.js
>      saveAdmins(updatedAdminList);
I would be missing a .then()

2022-11-10 18:39 UTC, LucianaPrat commented on src/Components/Admins/index.js
> +      {deleteModalDisplay ? (
{deleteModalDisplay && (...)}

2022-11-10 18:39 UTC, LucianaPrat commented on src/Components/Admins/index.js
> +      {errorModalDisplay ? (
same above

2022-11-10 20:05 UTC, GuidoG95 commented on src/Components/Admins/Form/index.js
> +      {modalDisplay ? (
done

2022-11-10 20:12 UTC, GuidoG95 commented on src/Components/Admins/index.js
> +      {deleteModalDisplay ? (
done

2022-11-10 20:12 UTC, GuidoG95 commented on src/Components/Admins/index.js
> +      {errorModalDisplay ? (
done

2022-11-10 20:12 UTC, GuidoG95 commented on src/Components/Admins/Form/index.js
> +          title={'Name'}
done

2022-11-10 20:12 UTC, GuidoG95 commented on src/Components/Admins/Form/index.js
> +          title={'Last Name'}
done

2022-11-10 20:19 UTC, GuidoG95 commented on src/Components/Admins/Form/index.js
> +  const [selectedAdmin] = useState(history.location.state);
done

2022-11-11 00:52 UTC, GuidoG95 commented on src/Components/Admins/index.js
>      saveAdmins(updatedAdminList);
done

2022-11-11 12:04 UTC, LucianaPrat approved these changes

2022-11-11 17:24 UTC, LucianaPrat approved these changes

2022-11-12 20:36 UTC, SantiagoGonzalez97 approved these changes

2022-11-12 20:41 UTC, merged