BaSP-TG-5: Projects page list and delete
BaSP-a2022/marta-a-trackgenix-app pull request #2
Opened 2022-11-01 04:13 UTC by GuidoG95

2022-11-01 14:55 UTC, martumoser requested changes
Please add a description to the PR

2022-11-01 14:55 UTC, martumoser commented on src/Components/Projects/index.js
> +  useEffect(() => {
Please leave a space between lines 8 and 9

2022-11-01 14:55 UTC, martumoser commented on src/Components/Projects/index.js
> +  function newEditProject(id) {
use const and arrow function instead of function

2022-11-01 14:55 UTC, martumoser commented on src/Components/Projects/form.js
> +  const editId = sessionStorage.getItem('editId');
You are using js methods to get the id instead of using react props. This form should receive the id of the selected item by props

2022-11-01 14:55 UTC, martumoser commented on src/Components/Projects/form.js
> +      .then((response) => console.log(response.data));
Why you are using this console log? It is not necessary

2022-11-01 14:55 UTC, martumoser commented on src/Components/Projects/Modal/modal.js
> +function Modal(props) {
use const and arrow function instead of function (ECMAScript 6)

2022-11-01 14:55 UTC, martumoser commented on src/Components/Projects/index.js
> +                <td className={styles.tableCell}>
Table and row table should be a react component as it was showing on the class. You can create a List component and a ListItem component

2022-11-01 15:30 UTC, GuidoG95 commented on src/Components/Projects/index.js
> +  useEffect(() => {
ok

2022-11-06 16:03 UTC, elias-92 commented on src/Components/Projects/Modal/modal.module.css
> +    background-color: white;
You should use rgb, to maintain consistency.

2022-11-06 16:04 UTC, elias-92 commented on src/Components/Projects/Modal/modal.module.css
> +    background-color: white;
You should use rgb, to maintain consistency.

2022-11-06 16:05 UTC, elias-92 commented on src/Components/Projects/index.js
> +  // const [employees, saveEmployees] = useState([]);
There should be no commented code.

2022-11-06 16:05 UTC, elias-92 commented on src/Components/Projects/index.js
> +    //   .then((response) => saveEmployees(response.data || []));
There should be no commented code

2022-11-06 16:07 UTC, elias-92 commented on src/Components/Projects/projects.module.css
> +  color: #373867;
You should use rgb, to maintain consistency.

2022-11-06 16:07 UTC, elias-92 commented on src/Components/Projects/projects.module.css
> +  color: #373867;
You should use rgb, to maintain consistency.

2022-11-06 16:08 UTC, elias-92 reviewed
Comments

2022-11-06 20:37 UTC, elias-92 approved these changes

2022-11-06 21:22 UTC, mr-valen commented
Missing feedback when assigning employee to project.

2022-11-06 21:28 UTC, mr-valen approved these changes
Employees assigned to project list is missing but it was already talked about to solve later.

2022-11-06 22:17 UTC, martumoser approved these changes

2022-11-06 22:23 UTC, merged