BaSP TG-33: Task components implementation
BaSP-a2022/marta-a-trackgenix-app pull request #21
Opened 2022-11-09 22:14 UTC by Baldizan

Shared Table, Button, Form, Inputs and Modal implementation into tasks' screens.

2022-11-10 21:56 UTC, LucianaPrat requested changes

2022-11-10 21:56 UTC, LucianaPrat commented on src/Components/Shared/Table/Row/index.js
>  const Row = ({ headers, rowItem, deleteItem, editItem }) => {
there should be no changes in this component

2022-11-10 21:56 UTC, LucianaPrat commented on src/Components/Shared/Table/index.js
>  import React from 'react';
there should be no changes in this component

2022-11-10 21:56 UTC, LucianaPrat commented on src/Components/Tasks/index.js
> +          theme={'confirm'}
the string should be with "" without {''}

2022-11-11 15:42 UTC, martumoser approved these changes

2022-11-11 16:16 UTC, LucianaPrat approved these changes

2022-11-11 23:42 UTC, mr-valen approved these changes
As far I see everything alright.

2022-11-11 23:44 UTC, merged