BaSP-TG-43: Admins redux GET
BaSP-a2022/marta-a-trackgenix-app pull request #26
Opened 2022-11-13 01:58 UTC by elias-92

Implement redux get, I left commented lines in the delete fetch because it skipped the eslint.

2022-11-13 02:40 UTC, GuidoG95 commented on src/Components/Admins/index.js
> +      // saveAdmins(updatedAdminList);
there should not be commented lines

2022-11-13 19:24 UTC, nailaghigo requested changes

2022-11-13 19:24 UTC, nailaghigo commented on src/redux/Admins/thunks.js
> +  return async (dispatch) => {
There is no need to add async/await to thunk actions. Please revert this changes

2022-11-13 19:42 UTC, elias-92 commented on src/redux/Admins/thunks.js
> +  return async (dispatch) => {
ok, fixed

2022-11-13 21:12 UTC, Baldizan commented on src/Components/Admins/index.js
> +      // saveAdmins(updatedAdminList);
Please remove these comments

2022-11-13 21:12 UTC, Baldizan commented on src/Components/Admins/index.js
>    }, []);
You can add "admins" as a dependancy here, so that the table fetches the data again when it changed.

2022-11-13 21:40 UTC, elias-92 commented on src/Components/Admins/index.js
> +      // saveAdmins(updatedAdminList);
ok

2022-11-13 21:41 UTC, Baldizan approved these changes

2022-11-13 22:01 UTC, LucianaPrat approved these changes

2022-11-14 01:36 UTC, nailaghigo approved these changes

2022-11-14 13:36 UTC, NicolasGulam approved these changes

2022-11-14 14:14 UTC, merged