BaSP-TG-7: Employees list and delete
BaSP-a2022/marta-a-trackgenix-app pull request #3
Opened 2022-11-01 13:01 UTC by Martinzancocchia

2022-11-02 19:53 UTC, martumoser requested changes
Please add a description to the PR

2022-11-02 19:53 UTC, martumoser commented on src/Components/Employees/index.js
> +      <table className={styles.table}>
The table and the rows should be another react component as was showing on the class.

2022-11-02 19:53 UTC, martumoser commented on src/Components/Employees/index.js
> +
Please don't leave comments on the PR. I think that you are using this lines of code on the other pr but they are not necessary on this pr

2022-11-02 19:53 UTC, martumoser commented on src/Components/Employees/index.js
> +  // eslint-disable-next-line no-unused-vars
please delete this comment

2022-11-02 19:53 UTC, martumoser commented on src/Components/Employees/Modal/modal.module.css
> +  background-color: rgba(0, 0, 0, 0.5);
please replace this color to color hex to keep consistency with the other colors

2022-11-02 19:53 UTC, martumoser commented on src/Components/Employees/Modal/index.js
> +  return (
please leave a space between lines 15 and 16

2022-11-02 19:53 UTC, martumoser commented on src/Components/Employees/Modal/index.js
> +        <small>Once deleted, the changes cannot be undone.</small>
avoid use this html element. You can use css to add styles to the elements

2022-11-02 23:48 UTC, Martinzancocchia commented on src/Components/Employees/index.js
> +
done

2022-11-02 23:48 UTC, Martinzancocchia commented on src/Components/Employees/index.js
> +  // eslint-disable-next-line no-unused-vars
done

2022-11-02 23:50 UTC, Martinzancocchia commented on src/Components/Employees/Modal/modal.module.css
> +  background-color: rgba(0, 0, 0, 0.5);
done

2022-11-02 23:51 UTC, Martinzancocchia commented on src/Components/Employees/Modal/index.js
> +  return (
done

2022-11-02 23:51 UTC, Martinzancocchia commented on src/Components/Employees/Modal/index.js
> +        <small>Once deleted, the changes cannot be undone.</small>
done

2022-11-03 11:44 UTC, martumoser requested changes

2022-11-03 11:44 UTC, martumoser commented on src/Components/Employees/List/index.js
> +const employeeList = (props) => {
Remember that react components starts with uppercase and also the list has some employee so it should be plural: EmployeesList

2022-11-03 11:44 UTC, martumoser commented on src/Components/Employees/List/index.js
> +const employeeList = (props) => {
Please destructure the props to know which are the props. Do the same that you did on Modal component

2022-11-03 11:44 UTC, martumoser commented on src/Components/Employees/Modal/index.js
> +          &times;
This is not necessary

2022-11-03 12:53 UTC, Martinzancocchia commented on src/Components/Employees/List/index.js
> +const employeeList = (props) => {
Done

2022-11-03 13:17 UTC, martumoser approved these changes

2022-11-03 16:00 UTC, merged