BaSP-TG-44: Redux Admins delete, create, edit.
BaSP-a2022/marta-a-trackgenix-app pull request #32
Opened 2022-11-15 16:49 UTC by elias-92

Implementation of redux in Admins:
-Put method
-Delete method
-Post method

2022-11-16 03:28 UTC, GuidoG95 commented on src/redux/Admins/thunks.js
> +    }
this is not working, it passing through the success modal altough there are errors in the fetch. I did it like:
if (json.error) {
          dispatch(putAdminError(json.message));
        } else {
          dispatch(putAdminSuccess());
          dispatch(getAdmin());
        }

2022-11-16 03:28 UTC, GuidoG95 commented on src/redux/Admins/reducer.js
> +    }
in every pending and success cases you should set "error: false" in order to reset error variable so it doesn't interfere with a new page load with a previous error

2022-11-16 13:10 UTC, LucianaPrat commented on src/redux/Admins/actions.js
> +export const deleteAdminSuccess = (payload) => {
I think the word Data is better than using payload

2022-11-16 17:15 UTC, GuidoG95 approved these changes

2022-11-16 22:35 UTC, Baldizan commented on src/Components/Admins/Form/index.js
> +  const [titleForm, setTitleForm] = useState('');
Is this state really needed?

2022-11-16 22:35 UTC, Baldizan commented on src/Components/Admins/Form/index.js
> +      setTitleForm('Add new admin');
This logic could be on the Form's title itself, using a ternary operator

2022-11-16 22:35 UTC, Baldizan commented on src/Components/Admins/Form/index.js
> +  }, [list]);
Is selectedAdmin an Id or an object with the selected admin's data?
On line 10, you could get the whole object, instead of just the id, and use that as your state, without useEffect.

2022-11-16 22:35 UTC, Baldizan commented on src/Components/Admins/Form/index.js
> +      dispatch(editAdmin(selectedAdmin, adminInput));
If you do apply changes based on the previous comment, this line needs to be chaged to "selectedAdmin._id"

2022-11-16 22:35 UTC, Baldizan commented on src/Components/Admins/index.js
> +    dispatch(deleteAdmin(selectedAdmin._id));
selectedAdmin is already an id, also based on line 10

2022-11-16 22:35 UTC, Baldizan commented on src/redux/Admins/thunks.js
> +  return async (dispatch) => {
As per redux documentation, "thunks do not know anything about async functions":

>_"By itself, a Redux store doesn't know anything about async logic. It only knows how to synchronously dispatch actions, update the state by calling the root reducer function, and notify the UI that something has changed. Any asynchronicity has to happen outside the store."_


 https://redux.js.org/tutorials/fundamentals/part-6-async-logic

2022-11-16 22:35 UTC, Baldizan commented on src/redux/Admins/thunks.js
> +export const deleteAdmin = (id) => {
All these functions could be exported at the end
Export {functionA, functionB, etc}

2022-11-16 22:35 UTC, Baldizan commented on src/redux/Admins/thunks.js
> +  return async (dispatch) => {
Note that when using async functions, people tend to use "then/catch", and "try/catch" when dealing with synchronous functions.

It may be a good idea to have a meeting with the other devs to discuss this subject.

2022-11-18 02:58 UTC, nailaghigo requested changes

2022-11-18 02:58 UTC, nailaghigo commented on src/redux/Admins/actions.js
> +};
You can add word EXPORT at the beginning of every function name to avoid writing these lines

2022-11-19 18:33 UTC, nailaghigo approved these changes

2022-11-19 20:20 UTC, mr-valen approved these changes
It works perfectly

2022-11-19 20:29 UTC, merged