BaSP-TG-50: Timesheet redux - GET
BaSP-a2022/marta-a-trackgenix-app pull request #36
Opened 2022-11-16 06:24 UTC by elias-92

Redux implementation to get timesheet:
-Create constants to get timesheets
-Create thunk to get timesheets
-Create timesheets reducer
-Connect list component with store to get timesheets

2022-11-16 16:55 UTC, LucianaPrat approved these changes

2022-11-16 19:53 UTC, nailaghigo requested changes

2022-11-16 19:53 UTC, nailaghigo commented on src/Components/TimeSheets/TimeSheetsTable/index.js
> +      {error && <p>Timesheets not found</p>}
We should display the error and not the text inside p tag

2022-11-17 22:33 UTC, Baldizan commented on src/redux/TimeSheets/reducer.js
> +        error: action.payload,
error: false should be declared on all non-error cases

2022-11-17 22:33 UTC, Baldizan commented on src/redux/TimeSheets/thunks.js
> +        dispatch(getTimeSheetsError(json.message));
without a return here, or an "if/else", the function will execute both dispatches (success and error) in case of error

2022-11-19 14:18 UTC, Baldizan commented on src/Components/TimeSheets/TimeSheetsForm/index.js
> +  // const dispatch = useDispatch();
Please remove comments

2022-11-19 14:18 UTC, Baldizan commented on src/Components/TimeSheets/TimeSheetsForm/index.js
> +  console.log(tasks);
Please remove console logs as well

2022-11-19 20:02 UTC, mr-valen approved these changes
Everything alright

2022-11-19 20:04 UTC, merged