BaSP-TG-2: Super Admin - Add/Edit Form
BaSP-a2022/marta-a-trackgenix-app pull request #4
Opened 2022-11-02 00:08 UTC by elias-92

2022-11-03 17:11 UTC, LucianaPrat commented on src/Components/SuperAdmins/Form/index.js
> +        headers: {
headers are not necessary

2022-11-03 17:18 UTC, LucianaPrat commented on src/Components/SuperAdmins/index.js
> +      console.log(error);
console log is not necessary

2022-11-03 18:33 UTC, martumoser requested changes

2022-11-03 18:33 UTC, martumoser commented on src/Components/SuperAdmins/Form/index.js
> +  const paramsURL = new URLSearchParams(window.location.search);
You have to use react props to get the id of the superadmin selected. The father component should sent the id of the superadmin selected as a prop.

2022-11-03 18:33 UTC, martumoser commented on src/Components/SuperAdmins/Form/index.js
> +  }, []);
Why you are doing this? this info about the super admin should be received as a prop

2022-11-03 18:33 UTC, martumoser commented on src/Components/SuperAdmins/Modal/index.js
> +const ModalDelete = ({ modal, setModal, deleteSuperAdmin }) => {
Why you are including this on this pr? delete functionality is on another PR

2022-11-04 12:56 UTC, martumoser approved these changes

2022-11-04 14:24 UTC, LucianaPrat approved these changes

2022-11-05 04:59 UTC, NicolasGulam commented
Done a simple comment in trello

2022-11-05 17:25 UTC, NicolasGulam approved these changes

2022-11-05 17:48 UTC, merged