BsSP-TG-10:  timesheet list / delete / add / edit
BaSP-a2022/marta-a-trackgenix-app pull request #5
Opened 2022-11-02 00:16 UTC by LucianaPrat

2022-11-02 01:33 UTC, martumoser requested changes

2022-11-02 01:33 UTC, martumoser commented on src/Components/TimeSheets/EditItem/EditItem.jsx
> +        console.log('data', json);
Please delete console.log

2022-11-02 01:33 UTC, martumoser commented on src/Components/TimeSheets/EditItem/EditItem.jsx
> +        console.log('data', json);
Please delete console.log

2022-11-02 01:33 UTC, martumoser commented on src/Components/TimeSheets/EditItem/EditItem.jsx
> +    console.log('e.target.value ', e.target.value);
Please delete all console.log

2022-11-02 01:33 UTC, martumoser commented on src/Components/TimeSheets/index.js
> +// import EditItem from './EditItem/EditItem';
Delete comments

2022-11-02 23:54 UTC, martumoser requested changes
Please add a description to the PR

2022-11-02 23:54 UTC, martumoser commented on src/Components/TimeSheets/index.js
> +    fetch(`http://localhost:5000/timesheets/${_id}`, {
Please replace localhost for env variables. The endpoint should impact on database. While you are creating or testing you code you can use localhost but the code which will be merge should impact on the database

2022-11-02 23:54 UTC, martumoser commented on src/Components/TimeSheets/index.js
> +    fetch('http://localhost:5000/timesheets')
Please replace localhost for env variables. The endpoint should impact on database. While you are creating or testing you code you can use localhost but the code which will be merge should impact on the database

2022-11-02 23:54 UTC, martumoser commented on src/Components/TimeSheets/Form/Form.jsx
> +    myHeaders.append('Content-Type', 'application/json');
this should not be necessary. I believe that the endpoints are not requiring headers

2022-11-03 17:30 UTC, elias-92 commented on src/Components/TimeSheets/ListItem/ListItem.css
> +  border: solid 0.5px rgb(204, 204, 204);
the color in this line should be hex since the others are like this.

2022-11-03 17:32 UTC, elias-92 commented on src/Components/TimeSheets/Modal/Modal.css
> +    background: rgba(0, 0, 0, .5);
the color in this line should be hex since the others are like this. and be careful with the identation.

2022-11-03 17:33 UTC, elias-92 commented on src/Components/TimeSheets/TimeSheetsForm/TimeSheetsForm.css
> + width: 30%;
Watch out for the identation

2022-11-03 17:34 UTC, elias-92 commented on src/Components/TimeSheets/time-sheets.module.css
> +  background-color: lightblue;
change the color format

2022-11-03 17:54 UTC, elias-92 reviewed
please revise comments

2022-11-04 13:00 UTC, martumoser approved these changes

2022-11-04 15:50 UTC, elias-92 approved these changes

2022-11-04 16:11 UTC, martumoser submitted a review, later dismissed
Edit functionality is not working and the employee name is not showing. Please fix that

2022-11-05 23:16 UTC, mr-valen approved these changes
Not loading date when editing a Timesheet.

2022-11-05 23:16 UTC, mr-valen commented on src/Components/TimeSheets/TimeSheetsForm/TimeSheetsForm.jsx
> +    console.log('aqui', projects);
Console.log

2022-11-05 23:16 UTC, mr-valen commented on src/Components/TimeSheets/TimeSheetsForm/TimeSheetsForm.jsx
> +  console.log(timeSheetInput.employee);
Console.log

2022-11-06 01:09 UTC, nailaghigo approved these changes

2022-11-06 16:26 UTC, merged