BaSP-TG-11: Admin Add and Edit
BaSP-a2022/marta-a-trackgenix-app pull request #7
Opened 2022-11-02 02:52 UTC by Baldizan

2022-11-04 04:47 UTC, elias-92 reviewed
reviewed.

2022-11-04 04:48 UTC, elias-92 reviewed
revised.

2022-11-04 12:47 UTC, LucianaPrat commented on src/Components/Admins/modal.module.css
> +    border-bottom: 1px solid rgba(0, 0, 0, 0.153);
the color in this line should be hex

2022-11-04 13:14 UTC, martumoser commented on src/Components/Admins/modal.module.css
> +    border-bottom: 1px solid rgba(0, 0, 0, 0.153);
not necessary in this case because with rgba color it is possible to add the opacity

2022-11-04 16:05 UTC, LucianaPrat approved these changes

2022-11-04 19:53 UTC, martumoser requested changes

2022-11-05 00:13 UTC, martumoser approved these changes

2022-11-05 20:43 UTC, Martinzancocchia approved these changes

2022-11-05 20:44 UTC, merged