BaSP-TG-12: Admin List and Delete
BaSP-a2022/marta-a-trackgenix-app pull request #8
Opened 2022-11-02 02:53 UTC by Baldizan

2022-11-02 20:15 UTC, martumoser requested changes
Please add a description to the PR

2022-11-02 20:15 UTC, martumoser commented on src/Components/Admins/modal.module.css
> +    background-color: #F13312;;
You have two semicolon at the end of the line. Please delete one

2022-11-02 20:15 UTC, martumoser commented on src/Components/Admins/modal.module.css
> +    max-width: 35ch;
why you are using ch unit?

2022-11-02 20:15 UTC, martumoser commented on src/Components/Admins/modal.module.css
> +}
are this properties necessary? they are the same of lines 48 to 53. Please put all together

2022-11-02 20:15 UTC, martumoser commented on src/Components/Admins/modal.module.css
> +  .heading {
Fix indentation

2022-11-02 20:15 UTC, martumoser commented on src/Components/Admins/index.js
>  function Admins() {
Replace for const and arrow function

2022-11-02 20:15 UTC, martumoser commented on src/Components/Admins/index.js
> +        <col span="5" className={styles.columns} />
Avoid use col element. Use css properties to add styles to the table

2022-11-02 20:15 UTC, martumoser commented on src/Components/Admins/index.js
> +      <table className={styles.table}>
Table and rows should be another react component as was showing on the class

2022-11-02 20:37 UTC, Baldizan commented on src/Components/Admins/modal.module.css
> +    max-width: 35ch;
.content is a <p> element, and "ch" makes determines the amount of charachters per line. Additionally, although responsiveness was not one of the task's requirements, "ch" enhances it.

2022-11-02 20:43 UTC, Baldizan commented on src/Components/Admins/modal.module.css
> +}
The scale is different for one and the other, because it does not look good otherwise.

2022-11-03 21:39 UTC, martumoser commented
pr descartada. Resuelto en en TG-11:Admin add and delete

2022-11-03 21:39 UTC, closed without merging